### ISSUE TITLE
better _post template

### ISSUE THREAD

**Issue by javaporter** [javaporter/roots-contentful-foundation#7]
If I extend layout in _post.jade, roots pukes because of the front matter (if I pull out all the frontmatter stuff in body class and head > title, it's fine). I must be doing this wrong. 

More specifically, lines from layout.jade like this: `title #{post.title} | Company` are causing the issue in _post.jade if I extend layout.

**Comment by jenius** [comment]
you have front matter in your post template?

**Comment by javaporter** [comment]
Hmm. Let me clarify, sorry for the confusion. I just pushed a new test, commit: 4d1119838d3f842857b5203801d1de20f8e1822f 

If roots watch is running and I add extends layout and block content to _post.jade, everything works fine. If I quit the process and restart roots, I get the following error: 

```

Cannot read property 'description' of undefined]

Potentially unhandled rejection [29] TypeError: /Users/pk/Sites/roots-contentful-foundation/views/layout.jade:7
    5|     meta(charset='utf8')
    6|     meta(http-equiv='X-UA-Compatible', content='IE=edge, chrome=1')
  > 7|     meta(name='description', content='#{post.description}')
    8|     meta(name="viewport", content="width=device-width, initial-scale=1")
    9|     title #{post.title} | Company
    10|     

Cannot read property 'description' of undefined
  at eval (<anonymous>:26:73)
  at eval (<anonymous>:195:22)
  at res (/Users/pk/Sites/roots-contentful-foundation/node_modules/jade/lib/index.js:219:38)
  at Object.exports.render (/Users/pk/Sites/roots-contentful-foundation/node_modules/jade/lib/index.js:349:43)
  at /usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:37:31
  at compile (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:70:15)
  at Jade._render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapters/jade.js:35:14)
  at Jade.Adapter.render (/usr/local/lib/node_modules/roots/node_modules/accord/lib/adapter_base.js:122:19)
  at Jade.wrapper (/usr/local/lib/node_modules/roots/node_modules/lodash/index.js:3580:19)
  at tryCatchReject (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:845:30)
  at runContinuation1 (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:804:4)
  at Fulfilled.when (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:592:4)
  at Pending.run (/usr/local/lib/node_modules/roots/node_modules/when/lib/makePromise.js:483:13)
  at Scheduler._drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:62:19)
  at Scheduler.drain (/usr/local/lib/node_modules/roots/node_modules/when/lib/Scheduler.js:27:9)
  at process._tickCallback (node.js:355:11)

```

To be clear, I am 100% aware that some of this is user error and I'm probably doing something wrong, just trying to figure out what. Jade templating (actually Jade in general) is new to me, I could just be doing this wrong.

**Comment by jenius** [comment]
Ah ok, yeah this is a jade usage thing. So you can't drop `#{post.description}` in `layout.jade` because it's used as the layout for other files that don't have `post.description` included in them, presumably. You need this just to be in `_post.jade`.

The way to solve this is to add another block where you can inject meta. So like you have a block for content, you just add another block for meta. You can see an example of using multiple blocks [here](http://jade-lang.com/reference/extends/). As you might notice in this example, you can also drop content into the block which will serve as the default if the block isn't present in a template that's being compiled into the layout, which is a very useful feature too.

Sorry for the confusion and good luck! I know you are working hard to get things up and running with roots, and how all these new languages can be frustrating, I definitely admire your dedication and am sorry that I take so long to respond these days (Im currently traveling which is the reason why). :tada:

**Comment by javaporter** [comment]
ok, thanks for the response. This works for now, but ideally what I'm looking for is something similar to this: `body class='#{page_classes}'`

that's what I'm used to in MM. There are ways to do this with JS, but it seems kind of hacky in comparison.

**Comment by jenius** [comment]
You can do this using the `_page` local, which will output the path to the page. Then just parse it through with a regex and grab the title. It's a quick one liner. I use this on nearly every site I build.
